name: build and deploy
run-name: deploying master after ${{ github.actor }} pushed updates
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run build

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUD_FRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update GitHub deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: https://d153lqu4o28h2l.cloudfront.net/
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update GitHub deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: https://d153lqu4o28h2l.cloudfront.net/
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
